/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnitsRouteImport } from './routes/units'
import { Route as TransfersRouteImport } from './routes/transfers'
import { Route as StrainsRouteImport } from './routes/strains'
import { Route as QcRouteImport } from './routes/qc'
import { Route as LineageRouteImport } from './routes/lineage'
import { Route as EventsRouteImport } from './routes/events'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnitsUnitCodeRouteImport } from './routes/units.$unitCode'
import { Route as TransfersNewRouteImport } from './routes/transfers.new'
import { Route as EventsNewRouteImport } from './routes/events.new'
import { Route as UnitsUnitCodeEditRouteImport } from './routes/units.$unitCode.edit'
import { Route as TransfersTransferIdEditRouteImport } from './routes/transfers.$transferId.edit'
import { Route as StrainsCodeEditRouteImport } from './routes/strains.$code.edit'
import { Route as EventsEventIdEditRouteImport } from './routes/events.$eventId.edit'

const UnitsRoute = UnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersRoute = TransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const StrainsRoute = StrainsRouteImport.update({
  id: '/strains',
  path: '/strains',
  getParentRoute: () => rootRouteImport,
} as any)
const QcRoute = QcRouteImport.update({
  id: '/qc',
  path: '/qc',
  getParentRoute: () => rootRouteImport,
} as any)
const LineageRoute = LineageRouteImport.update({
  id: '/lineage',
  path: '/lineage',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitsUnitCodeRoute = UnitsUnitCodeRouteImport.update({
  id: '/$unitCode',
  path: '/$unitCode',
  getParentRoute: () => UnitsRoute,
} as any)
const TransfersNewRoute = TransfersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TransfersRoute,
} as any)
const EventsNewRoute = EventsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => EventsRoute,
} as any)
const UnitsUnitCodeEditRoute = UnitsUnitCodeEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => UnitsUnitCodeRoute,
} as any)
const TransfersTransferIdEditRoute = TransfersTransferIdEditRouteImport.update({
  id: '/$transferId/edit',
  path: '/$transferId/edit',
  getParentRoute: () => TransfersRoute,
} as any)
const StrainsCodeEditRoute = StrainsCodeEditRouteImport.update({
  id: '/$code/edit',
  path: '/$code/edit',
  getParentRoute: () => StrainsRoute,
} as any)
const EventsEventIdEditRoute = EventsEventIdEditRouteImport.update({
  id: '/$eventId/edit',
  path: '/$eventId/edit',
  getParentRoute: () => EventsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events': typeof EventsRouteWithChildren
  '/lineage': typeof LineageRoute
  '/qc': typeof QcRoute
  '/strains': typeof StrainsRouteWithChildren
  '/transfers': typeof TransfersRouteWithChildren
  '/units': typeof UnitsRouteWithChildren
  '/events/new': typeof EventsNewRoute
  '/transfers/new': typeof TransfersNewRoute
  '/units/$unitCode': typeof UnitsUnitCodeRouteWithChildren
  '/events/$eventId/edit': typeof EventsEventIdEditRoute
  '/strains/$code/edit': typeof StrainsCodeEditRoute
  '/transfers/$transferId/edit': typeof TransfersTransferIdEditRoute
  '/units/$unitCode/edit': typeof UnitsUnitCodeEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events': typeof EventsRouteWithChildren
  '/lineage': typeof LineageRoute
  '/qc': typeof QcRoute
  '/strains': typeof StrainsRouteWithChildren
  '/transfers': typeof TransfersRouteWithChildren
  '/units': typeof UnitsRouteWithChildren
  '/events/new': typeof EventsNewRoute
  '/transfers/new': typeof TransfersNewRoute
  '/units/$unitCode': typeof UnitsUnitCodeRouteWithChildren
  '/events/$eventId/edit': typeof EventsEventIdEditRoute
  '/strains/$code/edit': typeof StrainsCodeEditRoute
  '/transfers/$transferId/edit': typeof TransfersTransferIdEditRoute
  '/units/$unitCode/edit': typeof UnitsUnitCodeEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events': typeof EventsRouteWithChildren
  '/lineage': typeof LineageRoute
  '/qc': typeof QcRoute
  '/strains': typeof StrainsRouteWithChildren
  '/transfers': typeof TransfersRouteWithChildren
  '/units': typeof UnitsRouteWithChildren
  '/events/new': typeof EventsNewRoute
  '/transfers/new': typeof TransfersNewRoute
  '/units/$unitCode': typeof UnitsUnitCodeRouteWithChildren
  '/events/$eventId/edit': typeof EventsEventIdEditRoute
  '/strains/$code/edit': typeof StrainsCodeEditRoute
  '/transfers/$transferId/edit': typeof TransfersTransferIdEditRoute
  '/units/$unitCode/edit': typeof UnitsUnitCodeEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events'
    | '/lineage'
    | '/qc'
    | '/strains'
    | '/transfers'
    | '/units'
    | '/events/new'
    | '/transfers/new'
    | '/units/$unitCode'
    | '/events/$eventId/edit'
    | '/strains/$code/edit'
    | '/transfers/$transferId/edit'
    | '/units/$unitCode/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/events'
    | '/lineage'
    | '/qc'
    | '/strains'
    | '/transfers'
    | '/units'
    | '/events/new'
    | '/transfers/new'
    | '/units/$unitCode'
    | '/events/$eventId/edit'
    | '/strains/$code/edit'
    | '/transfers/$transferId/edit'
    | '/units/$unitCode/edit'
  id:
    | '__root__'
    | '/'
    | '/events'
    | '/lineage'
    | '/qc'
    | '/strains'
    | '/transfers'
    | '/units'
    | '/events/new'
    | '/transfers/new'
    | '/units/$unitCode'
    | '/events/$eventId/edit'
    | '/strains/$code/edit'
    | '/transfers/$transferId/edit'
    | '/units/$unitCode/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsRoute: typeof EventsRouteWithChildren
  LineageRoute: typeof LineageRoute
  QcRoute: typeof QcRoute
  StrainsRoute: typeof StrainsRouteWithChildren
  TransfersRoute: typeof TransfersRouteWithChildren
  UnitsRoute: typeof UnitsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/units': {
      id: '/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof UnitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers': {
      id: '/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof TransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strains': {
      id: '/strains'
      path: '/strains'
      fullPath: '/strains'
      preLoaderRoute: typeof StrainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qc': {
      id: '/qc'
      path: '/qc'
      fullPath: '/qc'
      preLoaderRoute: typeof QcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lineage': {
      id: '/lineage'
      path: '/lineage'
      fullPath: '/lineage'
      preLoaderRoute: typeof LineageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/units/$unitCode': {
      id: '/units/$unitCode'
      path: '/$unitCode'
      fullPath: '/units/$unitCode'
      preLoaderRoute: typeof UnitsUnitCodeRouteImport
      parentRoute: typeof UnitsRoute
    }
    '/transfers/new': {
      id: '/transfers/new'
      path: '/new'
      fullPath: '/transfers/new'
      preLoaderRoute: typeof TransfersNewRouteImport
      parentRoute: typeof TransfersRoute
    }
    '/events/new': {
      id: '/events/new'
      path: '/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof EventsNewRouteImport
      parentRoute: typeof EventsRoute
    }
    '/units/$unitCode/edit': {
      id: '/units/$unitCode/edit'
      path: '/edit'
      fullPath: '/units/$unitCode/edit'
      preLoaderRoute: typeof UnitsUnitCodeEditRouteImport
      parentRoute: typeof UnitsUnitCodeRoute
    }
    '/transfers/$transferId/edit': {
      id: '/transfers/$transferId/edit'
      path: '/$transferId/edit'
      fullPath: '/transfers/$transferId/edit'
      preLoaderRoute: typeof TransfersTransferIdEditRouteImport
      parentRoute: typeof TransfersRoute
    }
    '/strains/$code/edit': {
      id: '/strains/$code/edit'
      path: '/$code/edit'
      fullPath: '/strains/$code/edit'
      preLoaderRoute: typeof StrainsCodeEditRouteImport
      parentRoute: typeof StrainsRoute
    }
    '/events/$eventId/edit': {
      id: '/events/$eventId/edit'
      path: '/$eventId/edit'
      fullPath: '/events/$eventId/edit'
      preLoaderRoute: typeof EventsEventIdEditRouteImport
      parentRoute: typeof EventsRoute
    }
  }
}

interface EventsRouteChildren {
  EventsNewRoute: typeof EventsNewRoute
  EventsEventIdEditRoute: typeof EventsEventIdEditRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsNewRoute: EventsNewRoute,
  EventsEventIdEditRoute: EventsEventIdEditRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

interface StrainsRouteChildren {
  StrainsCodeEditRoute: typeof StrainsCodeEditRoute
}

const StrainsRouteChildren: StrainsRouteChildren = {
  StrainsCodeEditRoute: StrainsCodeEditRoute,
}

const StrainsRouteWithChildren =
  StrainsRoute._addFileChildren(StrainsRouteChildren)

interface TransfersRouteChildren {
  TransfersNewRoute: typeof TransfersNewRoute
  TransfersTransferIdEditRoute: typeof TransfersTransferIdEditRoute
}

const TransfersRouteChildren: TransfersRouteChildren = {
  TransfersNewRoute: TransfersNewRoute,
  TransfersTransferIdEditRoute: TransfersTransferIdEditRoute,
}

const TransfersRouteWithChildren = TransfersRoute._addFileChildren(
  TransfersRouteChildren,
)

interface UnitsUnitCodeRouteChildren {
  UnitsUnitCodeEditRoute: typeof UnitsUnitCodeEditRoute
}

const UnitsUnitCodeRouteChildren: UnitsUnitCodeRouteChildren = {
  UnitsUnitCodeEditRoute: UnitsUnitCodeEditRoute,
}

const UnitsUnitCodeRouteWithChildren = UnitsUnitCodeRoute._addFileChildren(
  UnitsUnitCodeRouteChildren,
)

interface UnitsRouteChildren {
  UnitsUnitCodeRoute: typeof UnitsUnitCodeRouteWithChildren
}

const UnitsRouteChildren: UnitsRouteChildren = {
  UnitsUnitCodeRoute: UnitsUnitCodeRouteWithChildren,
}

const UnitsRouteWithChildren = UnitsRoute._addFileChildren(UnitsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsRoute: EventsRouteWithChildren,
  LineageRoute: LineageRoute,
  QcRoute: QcRoute,
  StrainsRoute: StrainsRouteWithChildren,
  TransfersRoute: TransfersRouteWithChildren,
  UnitsRoute: UnitsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
